21 lines (16 sloc)  306 Bytes
 
name: test

on:
  push:
    branches:
      - main

jobs:
  super-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute Super Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
